; RAM

M68K_RAM_Start                 equ $FFFF0000

SS_Ram_Layout_Address          equ M68K_RAM_Start+$4000

Level_Map_Buffer               equ M68K_RAM_Start+$8000
Level_Map_Bg_Buffer            equ Level_Map_Buffer+$80

Blocks_Mem_Address             equ M68K_RAM_Start+$9000

Obj_Memory_Address             equ M68K_RAM_Start+$B000
player1			equ Obj_Memory_Address
player1XPos		equ player1+obj.X
player1YPos		equ player1+obj.Y
player2			equ Obj_Memory_Address+$40
player2XPos		equ player2+obj.X
player2YPos		equ player2+obj.Y
Title_Card_RAM_Obj_Data        equ Obj_Memory_Address+$80
HUD_RAM_Obj_Data               equ Obj_Memory_Address+$0380
Level_Results_RAM_Obj_Data     equ Obj_Memory_Address+$05C0

Obj_Start_Addr_2P              equ M68K_RAM_Start+$BE00
Obj_Page_01_2P_Addr            equ M68K_RAM_Start+$C100
Obj_Page_02_2P_Addr            equ M68K_RAM_Start+$C400
Obj_Page_03_2P_Addr            equ M68K_RAM_Start+$C700
Obj_Page_04_2P_Addr            equ M68K_RAM_Start+$CA00
Obj_Page_05_2P_Addr            equ M68K_RAM_Start+$CD00

Special_Stage_Memory_Address   equ M68K_RAM_Start+$D000

Primary_Colision_Data_Buffer   equ M68K_RAM_Start+$D000
Secundary_Colision_Data_Buffer equ M68K_RAM_Start+$D600

DMA_Buffer_List                equ M68K_RAM_Start+$DC00
DMA_Buffer_List_End            equ M68K_RAM_Start+$DCFC

Scroll_Buffer_Data             equ M68K_RAM_Start+$E000
Camera_X                       equ M68K_RAM_Start+$EE00 
Camera_Y                       equ M68K_RAM_Start+$EE04 
Camera_X_x2                    equ M68K_RAM_Start+$EE08 
Camera_Y_x4                    equ M68K_RAM_Start+$EE0C 
Camera_Y_x4_Mod_10             equ M68K_RAM_Start+$EE14 
Camera_X_x8                    equ M68K_RAM_Start+$EE10 
Camera_X_x4                    equ M68K_RAM_Start+$EE18
Camera_Y_x4_Mod_10_2           equ M68K_RAM_Start+$EE1C 
Camera_X_2                     equ M68K_RAM_Start+$EE20 
Camera_Y_2                     equ M68K_RAM_Start+$EE24
Scroll_Flag_Array              equ M68K_RAM_Start+$EE50
Scroll_Flag_Array_2            equ M68K_RAM_Start+$EEA0
Horizontal_Scrolling           equ M68K_RAM_Start+$EEB0
Vertical_Scrolling             equ M68K_RAM_Start+$EEB2
Horizontal_Scrolling_Sub       equ M68K_RAM_Start+$EEB4
Vertical_Scrolling_Sub         equ M68K_RAM_Start+$EEB6
Sonic_Level_Limits_Min_X       equ M68K_RAM_Start+$EEC8
Sonic_Level_Limits_Max_X       equ M68K_RAM_Start+$EECA
Sonic_Level_Limits_Min_Y       equ M68K_RAM_Start+$EECC
Sonic_Level_Limits_Max_Y       equ M68K_RAM_Start+$EECE
Level_Scroll_Flag              equ M68K_RAM_Start+$EEDC
Vertical_Scroll_Flag           equ M68K_RAM_Start+$EEDE
Dyn_Resize_Routine             equ M68K_RAM_Start+$EEDF
Tails_Level_Limits_Min_X       equ M68K_RAM_Start+$EEF8
Tails_Level_Limits_Max_X       equ M68K_RAM_Start+$EEFA
Tails_Level_Limits_Max_Y       equ M68K_RAM_Start+$EEFE
Game_Mode                      equ M68K_RAM_Start+$F600
Control_Ports_Buffer_Data      equ M68K_RAM_Start+$F604
Timer_Count_Down               equ M68K_RAM_Start+$F614 
Horizontal_Interrupt_Count     equ M68K_RAM_Start+$F624
Scanlines_Count                equ M68K_RAM_Start+$F625
VBlank_Index                   equ M68K_RAM_Start+$F62A
Pause_Status                   equ M68K_RAM_Start+$F63A
dmaCmdLow                      equ M68K_RAM_Start+$F640
hIntFlag                       equ M68K_RAM_Start+$F644
waterLevel                     equ M68K_RAM_Start+$F646
Water_Level_Change             equ M68K_RAM_Start+$F648
Water_Level_New                equ M68K_RAM_Start+$F64A
PLC_Buffer                     equ M68K_RAM_Start+$F680
Refresh_Level_Layout           equ M68K_RAM_Start+$F720
Water_Level_Flag               equ M68K_RAM_Start+$F730
Boss_Animate_Buffer            equ M68K_RAM_Start+$F740
Boss_Move_Buffer               equ M68K_RAM_Start+$F750
sonicMaxSpeed                equ M68K_RAM_Start+$F760
sonicAccel             equ M68K_RAM_Start+$F762
sonicDecel             equ M68K_RAM_Start+$F764
Current_Colision_Pointer       equ M68K_RAM_Start+$F796
Boss_Defeated_Flag             equ M68K_RAM_Start+$F7A7
Boss_Flag                      equ M68K_RAM_Start+$F7AA
Player_Status_Flag             equ M68K_RAM_Start+$F7CA
Camera_X_pos_coarse            equ M68K_RAM_Start+$F7DA
Palette_Buffer                 equ M68K_RAM_Start+$FB00
Palette_Underwater_Buffer      equ M68K_RAM_Start+$FB80
Obj_respawn_index              equ M68K_RAM_Start+$FC00
Exception_Index                equ M68K_RAM_Start+$FC44
StackPointer                   equ M68K_RAM_Start+$FE00
Debug_Mode_Flag_Index          equ M68K_RAM_Start+$FE08
Level_Id                       equ M68K_RAM_Start+$FE10
Act_Id                         equ M68K_RAM_Start+$FE11
Life_Count                     equ M68K_RAM_Start+$FE12
Special_Stage_Id               equ M68K_RAM_Start+$FE16
Super_Sonic_Flag               equ M68K_RAM_Start+$FE19
Time_Over_Flag                 equ M68K_RAM_Start+$FE1A
Ring_Life_Flag                 equ M68K_RAM_Start+$FE1B
HUD_Life_Refresh_Flag          equ M68K_RAM_Start+$FE1C
HUD_Rings_Refresh_Flag         equ M68K_RAM_Start+$FE1D
HUD_Timer_Refresh_Flag         equ M68K_RAM_Start+$FE1E
HUD_Score_Refresh_Flag         equ M68K_RAM_Start+$FE1F
Ring_Count                     equ M68K_RAM_Start+$FE20
Time_Count                     equ M68K_RAM_Start+$FE22
Time_Count_Minutes             equ M68K_RAM_Start+$FE23
Time_Count_Seconds             equ M68K_RAM_Start+$FE24
Time_Count_CentiSeconds        equ M68K_RAM_Start+$FE25
Score_Count                    equ M68K_RAM_Start+$FE26
Shield_Flag                    equ M68K_RAM_Start+$FE2C
Invincibility_Flag             equ M68K_RAM_Start+$FE2D
Hi_Speed_Flag                  equ M68K_RAM_Start+$FE2E
Saved_Level_Flag               equ M68K_RAM_Start+$FE30
Emerald_Count                  equ M68K_RAM_Start+$FE57
Emerald_Collected_Flag_List    equ M68K_RAM_Start+$FE58
Object_Frame_Buffer            equ M68K_RAM_Start+$FEA0
tailsMaxSpeed                equ M68K_RAM_Start+$FEC0
tailsAccel             equ M68K_RAM_Start+$FEC2
tailsDecel             equ M68K_RAM_Start+$FEC4
Level_select_flag              equ M68K_RAM_Start+$FFD0
Two_Player_Flag                equ M68K_RAM_Start+$FFD8
Sound_Buffer_Id                equ M68K_RAM_Start+$FFE0
Auto_Control_Player_Flag       equ M68K_RAM_Start+$FFF0
Hardware_Id                    equ M68K_RAM_Start+$FFF8 
Debug_Mode_Active_Flag         equ M68K_RAM_Start+$FFFA 
Init_Flag                      equ M68K_RAM_Start+$FFFC